/**
 * Utility functions for 1-click WhatsApp & Email disaster notifications,
 * SOS dispatch formatting, and GPS navigation links.
 */

// Clean phone numbers into standard international format for WhatsApp (defaults to +91 if 10 digits)
export function sanitizePhoneForWhatsApp(phone) {
  if (!phone) return '';
  let cleaned = String(phone).replace(/[^0-9]/g, '');
  if (cleaned.length === 10) {
    cleaned = '91' + cleaned;
  }
  return cleaned;
}

// Generate Google Maps pin/navigation URL
export function getGoogleMapsLink(lat, lng) {
  if (!lat || !lng) return '';
  return `https://www.google.com/maps/search/?api=1&query=${lat},${lng}`;
}

// Generate Google Maps driving / boat navigation directions link
export function getGoogleMapsDirectionsLink(lat, lng) {
  if (!lat || !lng) return '';
  return `https://www.google.com/maps/dir/?api=1&destination=${lat},${lng}`;
}

/**
 * Creates a pre-filled WhatsApp link for an SOS distress request
 */
export function createWhatsAppSosLink(sos = {}, targetPhone = '') {
  const gMapsUrl = sos?.lat && sos?.lng ? getGoogleMapsLink(sos.lat, sos.lng) : '';
  const needsList = (sos?.needTypes || ['Rescue', 'Emergency Food & Water']).join(', ');

  const message = [
    `🚨 *CRITICAL FLOOD SOS ALERT* 🚨`,
    `--------------------------------`,
    `👤 *Victim Name:* ${sos?.victimName || 'Citizen in Distress'}`,
    `📞 *Contact Phone:* ${sos?.contactPhone || 'N/A'}`,
    `👥 *People Stranded:* ${sos?.peopleCount || 1} person(s)`,
    sos?.waterLevelFeet ? `🌊 *Estimated Water Level:* ~${sos.waterLevelFeet} ft` : '',
    `⚠️ *Urgency:* ${(sos?.urgency || 'HIGH').toUpperCase()}`,
    `📦 *Critical Needs:* ${needsList}`,
    sos?.address ? `📍 *Landmark/Address:* ${sos.address}` : '',
    sos?.description ? `📝 *Victim Note:* "${sos.description}"` : '',
    sos?.lat && sos?.lng ? `🌐 *GPS Coordinates:* ${sos.lat}, ${sos.lng}` : '',
    gMapsUrl ? `🗺️ *Google Maps Pin:* ${gMapsUrl}` : '',
    `--------------------------------`,
    `_Sent via SETU Disaster Relief & NGO Response Grid_`
  ]
    .filter(Boolean)
    .join('\n');

  const cleanPhone = sanitizePhoneForWhatsApp(targetPhone);
  if (cleanPhone) {
    return `https://wa.me/${cleanPhone}?text=${encodeURIComponent(message)}`;
  }
  return `https://api.whatsapp.com/send?text=${encodeURIComponent(message)}`;
}

/**
 * Creates a pre-filled Email link for an SOS distress request
 */
export function createEmailSosLink(sos = {}, targetEmail = 'disaster.response@redcross.org.in') {
  const gMapsUrl = sos?.lat && sos?.lng ? getGoogleMapsLink(sos.lat, sos.lng) : '';
  const needsList = (sos?.needTypes || ['Rescue', 'Emergency Food & Water']).join(', ');

  const subject = `[EMERGENCY SOS - ${sos?.urgency?.toUpperCase() || 'CRITICAL'}] Victim: ${sos?.victimName || 'Citizen'} (${sos?.peopleCount || 1} Stranded)`;

  const body = `SETU DISASTER RELIEF - EMERGENCY VICTIM SOS REPORT
==================================================

INCIDENT OVERVIEW:
- Victim / Family Head: ${sos?.victimName || 'Citizen in Distress'}
- Direct Contact Phone: ${sos?.contactPhone || 'N/A'}
- People Trapped / Affected: ${sos?.peopleCount || 1}
- Current Water Level: ~${sos?.waterLevelFeet || 0} feet
- Severity Urgency: ${(sos?.urgency || 'HIGH').toUpperCase()}
- Urgent Supplies/Assistance Needed: ${needsList}

LOCATION & GEOGRAPHY:
- Landmark/Address: ${sos?.address || 'Address provided via GPS'}
- GPS Latitude: ${sos?.lat || 'N/A'}
- GPS Longitude: ${sos?.lng || 'N/A'}
- Direct Google Maps Navigation: ${gMapsUrl || 'N/A'}

VICTIM MESSAGE / SITUATION REPORT:
"${sos?.description || 'Immediate flood rescue and relief assistance required.'}"

--------------------------------------------------
Please mobilize nearest NDRF, SDRF, Red Cross, or Volunteer Boat units immediately.
Generated by SETU Disaster Response Network.`;

  return `mailto:${targetEmail}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
}

/**
 * Creates a WhatsApp link for relief camp supply deficit / request
 */
export function createWhatsAppCampRequisitionLink(camp = {}, req = {}, targetPhone = '') {
  const safeCamp = camp || {};
  const safeReq = req || {};
  const gMapsUrl = safeCamp.lat && safeCamp.lng ? getGoogleMapsLink(safeCamp.lat, safeCamp.lng) : '';

  const message = [
    `⛺ *RELIEF CAMP SUPPLY REQUISITION* ⛺`,
    `--------------------------------------`,
    `🏛️ *Relief Shelter:* ${safeCamp.name || safeReq.campName || 'Emergency Shelter Hub'}`,
    `👤 *Coordinator:* ${safeReq.requestedBy || safeCamp.contactPerson || 'Camp Manager'} (${safeReq.contactPhone || safeCamp.contactPhone || 'N/A'})`,
    `📦 *Item Requested:* ${safeReq.item || safeReq.resource || 'Emergency Supplies'}`,
    `📊 *Quantity:* ${safeReq.quantity || 'Urgent Stock'}`,
    `⚠️ *Priority:* ${(safeReq.urgency || 'HIGH').toUpperCase()}`,
    safeReq.purpose ? `🎯 *Assigned Purpose:* "${safeReq.purpose}"` : '',
    safeReq.adminInstructions ? `📋 *Admin Directive:* "${safeReq.adminInstructions}"` : '',
    safeCamp.locationName ? `📍 *Camp Location:* ${safeCamp.locationName}` : '',
    gMapsUrl ? `🗺️ *Camp Google Maps Pin:* ${gMapsUrl}` : '',
    `--------------------------------------`,
    `_SETU Emergency Supply Dispatch Network_`
  ]
    .filter(Boolean)
    .join('\n');

  const cleanPhone = sanitizePhoneForWhatsApp(targetPhone);
  if (cleanPhone) {
    return `https://wa.me/${cleanPhone}?text=${encodeURIComponent(message)}`;
  }
  return `https://api.whatsapp.com/send?text=${encodeURIComponent(message)}`;
}

/**
 * Creates an Email link for relief camp supply requisition
 */
export function createEmailCampRequisitionLink(camp = {}, req = {}, targetEmail = '') {
  const safeCamp = camp || {};
  const safeReq = req || {};
  const subject = `[SUPPLY REQUISITION] ${safeCamp.name || safeReq.campName || 'Emergency Camp'} - ${safeReq.quantity || ''} ${safeReq.item || safeReq.resource || 'Supplies'}`;
  const body = `SETU RELIEF NETWORK - SUPPLY REQUISITION NOTICE
==============================================

CAMP DETAILS:
- Relief Camp: ${safeCamp.name || safeReq.campName || 'Designated Shelter Hub'}
- Location: ${safeCamp.locationName || 'Designated Shelter Hub'}
- Coordinator: ${safeReq.requestedBy || safeCamp.contactPerson || 'Camp Coordinator'} (${safeReq.contactPhone || safeCamp.contactPhone || 'N/A'})
- Capacity/Occupancy: ${safeCamp.currentOccupancy || 0}/${safeCamp.capacity || 0} Beds

SUPPLY REQUIREMENTS:
- Item: ${safeReq.item || safeReq.resource || 'Essential Relief Material'}
- Quantity: ${safeReq.quantity || 'Urgent Batch'}
- Urgency: ${(safeReq.urgency || 'HIGH').toUpperCase()}
- Operational Purpose: ${safeReq.purpose || 'Distribution to flood affected evacuees'}
- Admin Instructions / Directives: ${safeReq.adminInstructions || 'Pending admin allocation'}

Please confirm availability and dispatch schedule.
SETU Flood Supply Coordination Team`;

  return `mailto:${targetEmail}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
}
